package com.javapos.mainsale;

import javax.swing.table.DefaultTableModel;

import com.javapos.menu.MainMenu;
import com.javapos.menu.displayer.MenuItemDisplayer;
import com.javapos.menu.displayer.MenuPanelDisplayer;
import com.javapos.models.DBController;
import com.javapos.orders.CustomerOrder;

import java.util.ArrayList;

import javax.swing.JOptionPane;

/**
 *
 * @author nhom NullPointerException: Trung Nguyen va nhung nguoi ban, Lap trinh
 *         nang cao-L02-HK212
 * 
 */
public class MainPage extends javax.swing.JFrame {
	// 1 doi tuong textDatabse dung chung cho tat ca cac dich vu, dat trong
	// mainPage.
	static DBController mainTextDataBase = DBController.getCurrentDBSession();

	// Table Model cho table duy nhat cua main Page
	DefaultTableModel mainTableModel;

	MenuPanelDisplayer mpd;
	MainMenu mm;
	OrderViewer orderViewerPage;

	public MainPage() {
		initComponents();

		// Su dung 1 reference khac tham chieu den doi tuong hien tai cua class va dung
		// no thay cho "this"
		javax.swing.JFrame mainPagePointer = this;

		// Lam xuat hien mot pop-up xac nhan viec thoat chuong trinh cua nguoi dung
		mainPagePointer.addWindowListener(new java.awt.event.WindowAdapter() {
			@Override
			public void windowClosing(java.awt.event.WindowEvent winEve) {
				if (JOptionPane.showConfirmDialog(mainPagePointer, "Chắc chắn rằng bạn đã GHI LẠI DỮ LIỆU ĐƠN HÀNG!!",
						"Bạn muốn kết thúc chương trình??", JOptionPane.YES_NO_OPTION,
						JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
					System.exit(0);
				}
			}
		});

		// Nut chot don chi san sang khi don hang co the thanh toan
		this.chotDonButton.setEnabled(false);

		// Phan hien thi tong so tien se khong the nhan tin hieu chinh sưa tu ban phim
		this.totalAmountDisplayer.setEditable(false);
		this.needToReturnAmount.setEditable(false);

		this.mm = new MainMenu();

		this.orderViewerPage = new OrderViewer();
		this.orderViewerPage.setVisible(false);

		mpd = new MenuPanelDisplayer(jPanel1, mm);
		mpd.updateMenuPanelDisplayer();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		addNewItemToMenuDialog = new javax.swing.JDialog();
		addNewItemToMenuNote = new javax.swing.JLabel();
		newItemNameInput = new javax.swing.JTextField();
		newItemPriceInput = new javax.swing.JTextField();
		addNewItemToMenuInstruct1 = new javax.swing.JLabel();
		addNewItemToMenuInstruct2 = new javax.swing.JLabel();
		addNewItemToMenuInnerButton = new javax.swing.JButton();
		resultAddNewItemToMenu = new javax.swing.JDialog();
		messageResultAddNewItemToMenu = new javax.swing.JLabel();
		closeResultAddNewItemToMenu = new javax.swing.JButton();
		tieuDe = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		nutThemVao = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		table = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		totalAmountDisplayer = new javax.swing.JTextField();
		nutXoaDi = new javax.swing.JButton();
		chotDonButton = new javax.swing.JButton();
		soDienThoai = new javax.swing.JTextField();
		summaryButton = new javax.swing.JButton();
		addNewItemToMenuButton = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		mainPageInstruct1 = new javax.swing.JLabel();
		mainPageInstruct2 = new javax.swing.JLabel();
		customerPayAmount = new javax.swing.JTextField();
		needToReturnAmount = new javax.swing.JTextField();
		soTienKhachDua = new javax.swing.JLabel();
		soTienCanTra = new javax.swing.JLabel();
		printInvoiceButton = new javax.swing.JButton();
		customerPaymentOKButton = new javax.swing.JButton();

		addNewItemToMenuDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		addNewItemToMenuDialog.setTitle("Thêm món mới");
		addNewItemToMenuDialog.setLocation(new java.awt.Point(350, 180));
		addNewItemToMenuDialog.setMinimumSize(new java.awt.Dimension(496, 285));
		addNewItemToMenuDialog.setModal(true);

		addNewItemToMenuNote.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		addNewItemToMenuNote.setText(
				"<html>+ Nhập tên món và giá cả của món cần thêm và ấn nút.<br>+ Lưu ý, các từ trong tên món viết không dấu, cách nhau bằng '_'  ; giá cả chỉ viết số, không khoảng trắng, giá trị không >100 triệu.</html>");

		addNewItemToMenuInstruct1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		addNewItemToMenuInstruct1.setText("Tên món mới:");

		addNewItemToMenuInstruct2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		addNewItemToMenuInstruct2.setText("Giá món mới:");

		addNewItemToMenuInnerButton.setText("THÊM MÓN");
		addNewItemToMenuInnerButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addNewItemToMenuInnerButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout addNewItemToMenuDialogLayout = new javax.swing.GroupLayout(
				addNewItemToMenuDialog.getContentPane());
		addNewItemToMenuDialog.getContentPane().setLayout(addNewItemToMenuDialogLayout);
		addNewItemToMenuDialogLayout.setHorizontalGroup(addNewItemToMenuDialogLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(addNewItemToMenuDialogLayout.createSequentialGroup().addContainerGap(38, Short.MAX_VALUE)
						.addGroup(addNewItemToMenuDialogLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewItemToMenuDialogLayout
										.createSequentialGroup()
										.addGroup(addNewItemToMenuDialogLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(addNewItemToMenuInstruct1,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 85,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(addNewItemToMenuInstruct2,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 85,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(addNewItemToMenuDialogLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(newItemPriceInput, javax.swing.GroupLayout.DEFAULT_SIZE,
														219, Short.MAX_VALUE)
												.addComponent(newItemNameInput))
										.addGap(97, 97, 97))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewItemToMenuDialogLayout
										.createSequentialGroup()
										.addComponent(addNewItemToMenuNote, javax.swing.GroupLayout.PREFERRED_SIZE, 436,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(22, 22, 22))))
				.addGroup(addNewItemToMenuDialogLayout
						.createSequentialGroup().addGap(188, 188, 188).addComponent(addNewItemToMenuInnerButton,
								javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));
		addNewItemToMenuDialogLayout.setVerticalGroup(addNewItemToMenuDialogLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(addNewItemToMenuDialogLayout.createSequentialGroup().addContainerGap()
						.addComponent(addNewItemToMenuNote, javax.swing.GroupLayout.PREFERRED_SIZE, 66,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(31, 31, 31)
						.addGroup(addNewItemToMenuDialogLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(newItemNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(addNewItemToMenuInstruct1))
						.addGap(23, 23, 23)
						.addGroup(addNewItemToMenuDialogLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(addNewItemToMenuInstruct2).addComponent(newItemPriceInput,
										javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18).addComponent(addNewItemToMenuInnerButton,
								javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(39, Short.MAX_VALUE)));

		resultAddNewItemToMenu.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		resultAddNewItemToMenu.setTitle("Thông báo!!!");
		resultAddNewItemToMenu.setLocation(new java.awt.Point(370, 200));
		resultAddNewItemToMenu.setMinimumSize(new java.awt.Dimension(400, 300));
		resultAddNewItemToMenu.setModal(true);

		messageResultAddNewItemToMenu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

		closeResultAddNewItemToMenu.setText("ĐÓNG");
		closeResultAddNewItemToMenu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				closeResultAddNewItemToMenuActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout resultAddNewItemToMenuLayout = new javax.swing.GroupLayout(
				resultAddNewItemToMenu.getContentPane());
		resultAddNewItemToMenu.getContentPane().setLayout(resultAddNewItemToMenuLayout);
		resultAddNewItemToMenuLayout.setHorizontalGroup(resultAddNewItemToMenuLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(resultAddNewItemToMenuLayout.createSequentialGroup().addGroup(resultAddNewItemToMenuLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(resultAddNewItemToMenuLayout.createSequentialGroup().addGap(148, 148, 148)
								.addComponent(closeResultAddNewItemToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 94,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(resultAddNewItemToMenuLayout.createSequentialGroup().addGap(54, 54, 54).addComponent(
								messageResultAddNewItemToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 284,
								javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(62, Short.MAX_VALUE)));
		resultAddNewItemToMenuLayout.setVerticalGroup(resultAddNewItemToMenuLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(resultAddNewItemToMenuLayout.createSequentialGroup().addGap(42, 42, 42)
						.addComponent(messageResultAddNewItemToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 139,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
						.addComponent(closeResultAddNewItemToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(39, 39, 39)));

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setLocation(new java.awt.Point(300, 150));

		tieuDe.setBackground(new java.awt.Color(255, 255, 255));
		tieuDe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		tieuDe.setForeground(new java.awt.Color(0, 204, 0));
		tieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		tieuDe.setText("LTNC - L02 - HK212 - NullPointerException");

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 153), 2));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 256, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 356, Short.MAX_VALUE));

		nutThemVao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		nutThemVao.setText("THÊM ĐƠN HÀNG");
		nutThemVao.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nutThemVaoActionPerformed(evt);
			}
		});

		table.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "TÊN MÓN", "ĐƠN GIÁ", "SỐ LƯỢNG" }) {
			Class[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.String.class };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		table.getTableHeader().setReorderingAllowed(false);
		jScrollPane1.setViewportView(table);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 153, 51));
		jLabel1.setText("Tổng cộng:");

		totalAmountDisplayer.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				totalAmountDisplayerActionPerformed(evt);
			}
		});

		nutXoaDi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		nutXoaDi.setText("XÓA ĐƠN HIỆN TẠI");
		nutXoaDi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nutXoaDiActionPerformed(evt);
			}
		});

		chotDonButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		chotDonButton.setText("CHỐT ĐƠN");
		chotDonButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				chotDonButtonActionPerformed(evt);
			}
		});

		soDienThoai.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				soDienThoaiActionPerformed(evt);
			}
		});

		summaryButton.setText("TỔNG KẾT...");
		summaryButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				summaryButtonActionPerformed(evt);
			}
		});

		addNewItemToMenuButton.setText("THÊM MÓN MỚI");
		addNewItemToMenuButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addNewItemToMenuButtonActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel2.setText("SĐT Khách hàng:");

		mainPageInstruct1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
		mainPageInstruct1.setText("*Để xóa đi một món ăn trong thực đơn, cần truy cập file và xóa thủ công.");

		mainPageInstruct2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
		mainPageInstruct2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		mainPageInstruct2.setText(
				"<html>Chỉnh số lượng về '-1' rồi ấn nút hiển thị tên món để đánh dấu \"hết món\"<br>Khởi động lại để hoàn tác."); // NOI18N
		mainPageInstruct2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		customerPayAmount.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				customerPayAmountActionPerformed(evt);
			}
		});

		needToReturnAmount.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				needToReturnAmountActionPerformed(evt);
			}
		});

		soTienKhachDua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		soTienKhachDua.setForeground(new java.awt.Color(0, 204, 51));
		soTienKhachDua.setText("Số tiền khách đưa:");

		soTienCanTra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		soTienCanTra.setForeground(new java.awt.Color(0, 153, 153));
		soTienCanTra.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		soTienCanTra.setText("Số tiền cần trả:");

		printInvoiceButton.setText("IN HÓA ĐƠN(waiting)");
		printInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				printInvoiceButtonActionPerformed(evt);
			}
		});

		customerPaymentOKButton.setText("OK");
		customerPaymentOKButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				customerPaymentOKButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(addNewItemToMenuButton)
						.addGap(29, 29, 29)
						.addComponent(tieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 534,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(summaryButton, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(printInvoiceButton, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap())
				.addGroup(layout.createSequentialGroup().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(42, 42, 42).addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(46, 46, 46)
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(layout.createSequentialGroup()
														.addComponent(chotDonButton,
																javax.swing.GroupLayout.PREFERRED_SIZE, 149,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36,
																Short.MAX_VALUE)
														.addComponent(jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE, 290,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(nutXoaDi, javax.swing.GroupLayout.DEFAULT_SIZE,
																149, Short.MAX_VALUE)
														.addComponent(nutThemVao, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGroup(layout.createSequentialGroup().addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(soDienThoai,
																javax.swing.GroupLayout.PREFERRED_SIZE, 112,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
																101, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(61, 61, 61)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																.addComponent(jLabel1,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(soTienCanTra,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(soTienKhachDua,
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 122,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(18, 18, 18)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																.addComponent(needToReturnAmount)
																.addComponent(totalAmountDisplayer,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 99,
																		Short.MAX_VALUE)
																.addComponent(customerPayAmount))
														.addGap(2, 2, 2).addComponent(customerPaymentOKButton,
																javax.swing.GroupLayout.PREFERRED_SIZE, 49,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGroup(layout.createSequentialGroup()
										.addComponent(mainPageInstruct1, javax.swing.GroupLayout.PREFERRED_SIZE, 371,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(195, 195, 195))))
						.addGroup(layout.createSequentialGroup().addGap(21, 21, 21).addComponent(mainPageInstruct2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup().addGap(36, 36, 36).addComponent(addNewItemToMenuButton))
						.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(summaryButton)
								.addGap(18, 18, 18).addComponent(printInvoiceButton))
						.addComponent(tieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 77,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(1, 1, 1)
				.addComponent(mainPageInstruct2, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(mainPageInstruct1))
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
										layout.createSequentialGroup().addGap(11, 11, 11)
												.addComponent(nutThemVao, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(nutXoaDi, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(42, 42, 42).addComponent(chotDonButton,
														javax.swing.GroupLayout.PREFERRED_SIZE, 46,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(18, 18, 18).addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel1).addComponent(
																totalAmountDisplayer,
																javax.swing.GroupLayout.PREFERRED_SIZE, 42,
																javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(layout.createSequentialGroup().addGroup(layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				customerPayAmount,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				28,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(customerPaymentOKButton))
																		.addGap(13, 13, 13))
																.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																		layout.createSequentialGroup()
																				.addComponent(soTienKhachDua)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(needToReturnAmount)
																.addComponent(soTienCanTra))
														.addGap(16, 16, 16))
												.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
														.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
																20, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(soDienThoai,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(36, 36, 36)))))));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void totalAmountDisplayerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_totalAmountDisplayerActionPerformed

	}// GEN-LAST:event_totalAmountDisplayerActionPerformed

	private void nutThemVaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nutThemVaoActionPerformed

		this.mainTableModel = (DefaultTableModel) table.getModel();
		this.mainTableModel.setRowCount(0);

		ArrayList<MenuItemDisplayer> menuItemDisplayer = mpd.getMainMenuDisplayerList();

		Integer totalPrice = 0;

		for (var item : menuItemDisplayer) {
			int valueFromSpinner = item.getValueFromSpinner();

			if (valueFromSpinner > 0) {
				String[] nameAndPrice = item.getText().split(" ");

				this.mainTableModel
						.addRow(new Object[] { nameAndPrice[0], nameAndPrice[1], Integer.toString(valueFromSpinner) });

				totalPrice += valueFromSpinner * Integer.valueOf(nameAndPrice[1]);
			}

		}

		this.totalAmountDisplayer.setText(Integer.toString(totalPrice));
	}// GEN-LAST:event_nutThemVaoActionPerformed

	private void nutXoaDiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nutXoaDiActionPerformed
		// TODO add your handling code here:
		this.mainTableModel = (DefaultTableModel) table.getModel();

		this.mainTableModel.setRowCount(0);

		this.totalAmountDisplayer.setText("");
		this.soDienThoai.setText("");
		this.customerPayAmount.setText("");
		this.needToReturnAmount.setText("");

		// Nut nay chi san sang khi don hang co the thanh toan
		this.chotDonButton.setEnabled(false);
	}// GEN-LAST:event_nutXoaDiActionPerformed

	private void chotDonButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chotDonButtonActionPerformed
		// TODO add your handling code here:

		CustomerOrder tempOrder = new CustomerOrder();

		String phoneNumberFromMenu = "unknown";
		try {
			phoneNumberFromMenu = this.soDienThoai.getText();
		} catch (NullPointerException except) {
			phoneNumberFromMenu = "unknown";
		} finally {
			if (phoneNumberFromMenu.equals("")) {
				phoneNumberFromMenu = "unknown";
			}
		}

		String totalPriceFromMenu = "0";
		try {
			totalPriceFromMenu = this.totalAmountDisplayer.getText();
		} catch (NullPointerException excep) {
			// Ta loai bo cac don hang rong va khong ghi chung vao danh sach
//            System.out.println("Order khong ton tai mat hang nao.");
			return;
		} finally {
			// Ta loai bo cac don hang rong va khong ghi chung vao danh sach
			if (totalPriceFromMenu.equals("") || totalPriceFromMenu.equals("0") || totalPriceFromMenu.equals("-1")) {
//                System.out.println("Order khong ton tai mat hang nao.");
				return;
			}
		}

		tempOrder.setUpOrderInfo(phoneNumberFromMenu, totalPriceFromMenu);

		this.orderViewerPage.currentSessionHistory.addNewOrderToHistory(tempOrder);

		// Reset cac Component ve trang thai cu sau khi an nut chot don.
		DefaultTableModel dfm = (DefaultTableModel) this.table.getModel();
		dfm.setRowCount(0);

		this.soDienThoai.setText("");
		this.totalAmountDisplayer.setText("");
		this.customerPayAmount.setText("");
		this.needToReturnAmount.setText("");

		// Nut nay chi an duoc khi don hang dang o trang thai co the thanh toan
		this.chotDonButton.setEnabled(false);
	}// GEN-LAST:event_chotDonButtonActionPerformed

	private void soDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_soDienThoaiActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_soDienThoaiActionPerformed

	private void summaryButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_summaryButtonActionPerformed
		// TODO add your handling code here:
		if (!this.orderViewerPage.isVisible()) // Neu cua so chua mo(Visible = false), ta set Visible la true
		{
			this.orderViewerPage.setVisible(true);
		}

		this.orderViewerPage.renewAndShowOrderViewer();
	}// GEN-LAST:event_summaryButtonActionPerformed

	private void addNewItemToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addNewItemToMenuButtonActionPerformed

		this.addNewItemToMenuDialog.setVisible(true);
	}// GEN-LAST:event_addNewItemToMenuButtonActionPerformed

	private void addNewItemToMenuInnerButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addNewItemToMenuInnerButtonActionPerformed

		String newItemNameToAdd = this.newItemNameInput.getText();
		String newItemPriceToAdd = this.newItemPriceInput.getText();

		// Kiem tra tinh dung dan cua input

		boolean check = MainPage.mainTextDataBase.writeNewMenuItemIntoDB(newItemNameToAdd, newItemPriceToAdd);

		// Tuy ket qua cua viec viet them mon vao menu trong database ma cho ra cac
		// thong bao khac nhau
		if (!check) {
			this.messageResultAddNewItemToMenu.setText(
					"<html>- Thêm món mới KHÔNG thành công!!!<br><br>- Hãy xem lại cách đặt tên, giá cả,... hoặc kiểm tra lại hệ thống<\\html>");
			this.resultAddNewItemToMenu.setVisible(true);
		} else {
			this.messageResultAddNewItemToMenu.setText(
					"<html>- Thêm món mới thành công!!!<br><br>- KHỞI ĐỘNG LẠI phần mềm để được ghi nhận kết quả.<br><br>- Trước khi khởi động lại, chắc chắn rằng bạn đã LƯU LẠI DỮ LIỆU ĐƠN HÀNG.<\\html>");
			this.resultAddNewItemToMenu.setVisible(true);
		}
	}// GEN-LAST:event_addNewItemToMenuInnerButtonActionPerformed

	private void closeResultAddNewItemToMenuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_closeResultAddNewItemToMenuActionPerformed

		this.resultAddNewItemToMenu.dispose();
		this.addNewItemToMenuDialog.dispose();
	}// GEN-LAST:event_closeResultAddNewItemToMenuActionPerformed

	private void customerPayAmountActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_customerPayAmountActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_customerPayAmountActionPerformed

	private void needToReturnAmountActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_needToReturnAmountActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_needToReturnAmountActionPerformed

	private void printInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_printInvoiceButtonActionPerformed
		// Dang cho duoc implement do phu thuoc vao thiet bi in dau ra
	}// GEN-LAST:event_printInvoiceButtonActionPerformed

	private void customerPaymentOKButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_customerPaymentOKButtonActionPerformed

		// Input nhap vao phan "So tien khach hang dua" co the khong hop le
		String customerPaymentAmount = this.customerPayAmount.getText();
		String totalCost = this.totalAmountDisplayer.getText();

		if (customerPaymentAmount != null && !customerPaymentAmount.equals("") && totalCost != null
				&& !totalCost.equals("") && !totalCost.equals("0")) {
			// Neu truong hop don hang khong co hoa don nao thi khong tinh

			try {
				int pay = Integer.parseInt(customerPaymentAmount);
				int cost = Integer.parseInt(totalCost);

				int returnAmount = pay - cost;

				if (returnAmount < 0) {
					this.needToReturnAmount.setText("Khong du tien!");
				} else {
					this.needToReturnAmount.setText(Integer.toString(returnAmount));
					this.chotDonButton.setEnabled(true);
				}
			} catch (NumberFormatException except) {
				this.needToReturnAmount.setText("Khong hop le!");

			}
			// Neu doan code throw Exception, "So tien khach hang dua" da bi nhap sai.
		}

	}// GEN-LAST:event_customerPaymentOKButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainPage().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addNewItemToMenuButton;
	private javax.swing.JDialog addNewItemToMenuDialog;
	private javax.swing.JButton addNewItemToMenuInnerButton;
	private javax.swing.JLabel addNewItemToMenuInstruct1;
	private javax.swing.JLabel addNewItemToMenuInstruct2;
	private javax.swing.JLabel addNewItemToMenuNote;
	private javax.swing.JButton chotDonButton;
	private javax.swing.JButton closeResultAddNewItemToMenu;
	private javax.swing.JTextField customerPayAmount;
	private javax.swing.JButton customerPaymentOKButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel mainPageInstruct1;
	private javax.swing.JLabel mainPageInstruct2;
	private javax.swing.JLabel messageResultAddNewItemToMenu;
	private javax.swing.JTextField needToReturnAmount;
	private javax.swing.JTextField newItemNameInput;
	private javax.swing.JTextField newItemPriceInput;
	private javax.swing.JButton nutThemVao;
	private javax.swing.JButton nutXoaDi;
	private javax.swing.JButton printInvoiceButton;
	private javax.swing.JDialog resultAddNewItemToMenu;
	private javax.swing.JTextField soDienThoai;
	private javax.swing.JLabel soTienCanTra;
	private javax.swing.JLabel soTienKhachDua;
	private javax.swing.JButton summaryButton;
	private javax.swing.JTable table;
	private javax.swing.JLabel tieuDe;
	private javax.swing.JTextField totalAmountDisplayer;
	// End of variables declaration//GEN-END:variables
}
